[package]
name = "howitzer"
description = "Binary crate for the Howitzer Fault Proof VM"
edition = "2021"

version.workspace = true
authors.workspace = true

[dependencies]
# workspace
anyhow.workspace = true
alloy-primitives.workspace = true
serde.workspace = true
serde_json.workspace = true

# External
clap = { version = "4.5.9", features = ["derive"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"

# Local
howitzer-kernel = { path = "../crates/kernel" }
howitzer-fpvm = { path = "../crates/fpvm" }

[[bin]]
name = "howitzer"
path = "src/howitzer.rs"
